// <auto-generated />
using System;
using DDRScoring.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDRScoring.Migrations
{
    [DbContext(typeof(DDRScoringContext))]
    [Migration("20211030231312_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DDRScoring.Data.Entities.CaloriesBurned", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("CaloriesBurned");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.HighScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Disqualified")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HighScoreListId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HoldNoteScoresId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LifeRemainingSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("int");

                    b.Property<string>("Modifiers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PeakComboAward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PercentDP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("RadarValuesId")
                        .HasColumnType("bigint");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("StageAward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SurviveSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("TapNoteScoresId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HighScoreListId");

                    b.HasIndex("HoldNoteScoresId");

                    b.HasIndex("RadarValuesId");

                    b.HasIndex("TapNoteScoresId");

                    b.ToTable("HighScores");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.HighScoreList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HighGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastPlayed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumTimesPlayed")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("HighScoreList");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.HoldNoteScores", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Held")
                        .HasColumnType("int");

                    b.Property<int>("LetGo")
                        .HasColumnType("int");

                    b.Property<int>("MissedHold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HoldNoteScores");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.RadarValues", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Air")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Chaos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Fakes")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Freeze")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Hands")
                        .HasColumnType("bigint");

                    b.Property<long>("Holds")
                        .HasColumnType("bigint");

                    b.Property<long>("Jumps")
                        .HasColumnType("bigint");

                    b.Property<long>("Lifts")
                        .HasColumnType("bigint");

                    b.Property<long>("Mines")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Notes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Rolls")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Stream")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TapsAndHolds")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RadarValues");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.Song", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.Steps", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HigScoreListId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SongId")
                        .HasColumnType("bigint");

                    b.Property<string>("StepsType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HigScoreListId");

                    b.HasIndex("SongId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.TapNoteScores", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AvoidMine")
                        .HasColumnType("bigint");

                    b.Property<long>("CheckpointHit")
                        .HasColumnType("bigint");

                    b.Property<long>("CheckpointMiss")
                        .HasColumnType("bigint");

                    b.Property<long>("HitMine")
                        .HasColumnType("bigint");

                    b.Property<long>("Miss")
                        .HasColumnType("bigint");

                    b.Property<long>("W1")
                        .HasColumnType("bigint");

                    b.Property<long>("W2")
                        .HasColumnType("bigint");

                    b.Property<long>("W3")
                        .HasColumnType("bigint");

                    b.Property<long>("W4")
                        .HasColumnType("bigint");

                    b.Property<long>("W5")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TapNoteScores");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.CaloriesBurned", b =>
                {
                    b.HasOne("DDRScoring.Data.Entities.Player", null)
                        .WithMany("CaloriesBurneds")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.HighScore", b =>
                {
                    b.HasOne("DDRScoring.Data.Entities.HighScoreList", null)
                        .WithMany("HighScore")
                        .HasForeignKey("HighScoreListId");

                    b.HasOne("DDRScoring.Data.Entities.HoldNoteScores", "HoldNoteScores")
                        .WithMany()
                        .HasForeignKey("HoldNoteScoresId");

                    b.HasOne("DDRScoring.Data.Entities.RadarValues", "RadarValues")
                        .WithMany()
                        .HasForeignKey("RadarValuesId");

                    b.HasOne("DDRScoring.Data.Entities.TapNoteScores", "TapNoteScores")
                        .WithMany()
                        .HasForeignKey("TapNoteScoresId");

                    b.Navigation("HoldNoteScores");

                    b.Navigation("RadarValues");

                    b.Navigation("TapNoteScores");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.Song", b =>
                {
                    b.HasOne("DDRScoring.Data.Entities.Player", null)
                        .WithMany("Songs")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.Steps", b =>
                {
                    b.HasOne("DDRScoring.Data.Entities.HighScoreList", "HigScoreList")
                        .WithMany()
                        .HasForeignKey("HigScoreListId");

                    b.HasOne("DDRScoring.Data.Entities.Song", null)
                        .WithMany("Steps")
                        .HasForeignKey("SongId");

                    b.Navigation("HigScoreList");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.HighScoreList", b =>
                {
                    b.Navigation("HighScore");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.Player", b =>
                {
                    b.Navigation("CaloriesBurneds");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("DDRScoring.Data.Entities.Song", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
